# Generated by Django 6.0.7 on 2026-08-04 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoAstronomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESTRELLA', 'Estrella'), ('PLANETA', 'Planeta'), ('GALAXIA', 'Galaxia'), ('NEBULOSA', 'Nebulosa'), ('ASTEROIDE', 'Asteroide'), ('COMETA', 'Cometa')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('constelacion', models.CharField(max_length=100)),
                ('fecha_descubrimiento', models.DateField(default=datetime.date.today)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
